name: Deploy Feria del Grito a Firebase Hosting

on:
  push:
    branches: [main]
    paths:
      - 'feria-del-grito/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy a Firebase Hosting (feria-del-grito)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RETO_DIGITAL_BMM }}'
          projectId: reto-digital-bmm
          target: feria-del-grito
          entryPoint: feria-del-grito
          channelId: live
